spring:
  application:
    name: wbs-client
  main:
    banner-mode: "OFF"

server:
  port: 8002
  ssl:
    trust-store: classpath:wbs-client-server.jks
    trust-store-password: StrongPsw321

ws:
  port: 8001
  path: /wbs
  send-interval: 2