spring:
  application:
    name: wbs-client
  main:
    banner-mode: "OFF"

server:
  port: 8002
  ssl:
    trust-store: classpath:wbs-client-server.jks
    trust-store-password: StrongPsw321
    key-store-type: JKS
    key-store: classpath:wbs-client-server.jks
    key-store-password: StrongPsw321
    key-alias: wbs-client-server
    enabled: true

ws:
  server-host: ${SERVER_HOST}
  port: 8001
  path: /wbs
  send-interval: 1
