spring:
  application:
    name: wbs-server
  main:
    banner-mode: "OFF"

  datasource:
    url: jdbc:postgresql://localhost:5432/wbs_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8001

ws:
  path: /wbs